import { render } from 'vike/abort';

import { publicOrigin } from '../../services/api.js';
import { searchProducts } from '../../services/catalog.service.js';
import { isLocale } from '../../utils/locales.js';

const COPY = {
  en: {
    title: 'Search — Marvel',
    heading: 'Search',
    placeholder: 'Search for a product',
    submit: 'Search',
    results: 'results',
    empty: 'Nothing matched that search.',
    emptyHint: 'Try a shorter word, or check the spelling.',
    prompt: 'Type something to search the shop.',
    resultsFor: 'Results for',
  },
  ar: {
    title: 'البحث — مارفل',
    heading: 'البحث',
    placeholder: 'ابحث عن منتج',
    submit: 'بحث',
    results: 'نتيجة',
    empty: 'لا توجد نتائج مطابقة.',
    emptyHint: 'جرّب كلمة أقصر، أو تحقّق من الإملاء.',
    prompt: 'اكتب شيئًا للبحث في المتجر.',
    resultsFor: 'نتائج البحث عن',
  },
};

/**
 * Server-rendered, and noindex.
 *
 * Rendered on the server because a search URL is a real address: it can be
 * linked, shared and reloaded, and a shopper who sends a friend a search result
 * should not send them a blank page that fills in later.
 *
 * `noindex` because a search results page is not content. Letting a crawler in
 * produces an unbounded set of thin, near-duplicate URLs generated by whatever
 * anybody ever typed -- the classic way a shop spends its crawl budget on
 * nothing. The products themselves are indexed on their own pages.
 */
export async function data(pageContext) {
  const { locale } = pageContext.routeParams;
  if (!isLocale(locale)) throw render(404);

  const params = new URLSearchParams(pageContext.urlParsed?.searchOriginal ?? '');
  const q = (params.get('q') ?? '').trim();
  const page = Number.parseInt(params.get('page') ?? '1', 10);

  // An empty box is not an error and not a request for the catalogue: the page
  // renders its prompt without asking the API anything.
  const listing = q
    ? await searchProducts(locale, { q, page: Number.isNaN(page) ? 1 : page })
    : { items: [], total: 0, page: 1, query: '', item_list_id: 'search' };

  return {
    locale,
    q,
    listing,
    copy: COPY[locale] ?? COPY.en,
    head: {
      title: q ? `${q} — ${(COPY[locale] ?? COPY.en).heading}` : (COPY[locale] ?? COPY.en).title,
      canonical: `${publicOrigin()}/${locale}/search`,
      noindex: true,
    },
  };
}
